version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: jewelry_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jewelry_store
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: jewelry_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/jewelry_store
      SECRET_KEY: lumiere-secret-2024
    volumes:
       - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
